name: Frontend Deploy to EC2

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Frontend to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            cd /home/ubuntu/ImgBellProject/imgbellfront

            # Git 업데이트 (로컬 변경사항 무시하고 강제 업데이트)
            git fetch origin
            git reset --hard origin/main

            # 프론트엔드 서비스 재시작
            cd /home/ubuntu/ImgBellProject
            sudo docker-compose stop frontend
            sudo docker-compose rm -f frontend
            sudo docker-compose build frontend
            sudo docker-compose up -d frontend
