name: Frontend Deploy to EC2

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Frontend to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/ImgBellProject/ImgBellFront

            # Git 업데이트
            git pull origin main || git pull origin master

            # 프론트엔드 서비스 재시작
            cd /home/ubuntu/ImgBellProject
            docker-compose stop frontend
            docker-compose rm -f frontend
            docker-compose build frontend
            docker-compose up -d frontend

            # 불필요한 이미지 정리
            docker system prune -f
